### PR TITLE
Added a sliding feature

### LINKED ISSUE #12: Swipe between activity
Addition of swiping or sliding features between the four activity namely, activity_onboarding1.xml, activity_onboarding2.xml, activity_onboarding3.xml, activity_onboarding4.xml,. This will enable the user to move forward from one activity to another not only by the next button provided but also by swiping the screens.

### PR DESCRIPTION
**Pull request by shivjyotigarai**
Added this feature such that the user can move from one activity to another not only by the next button provided but also by swiping the screens....    :)

### CODE REVIEW

**Comment by shivjyotigarai** [comment]
@supu2701 should I post a short G.I.F or video showing the swipe feature 😊

**Comment by shivjyotigarai** [comment]
@supu2701 is the code working fine? 😊😊

**Comment by shivjyotigarai** [comment]
HERE I HAVE ADDED THE VIDEO SHOWING THE SWIPE FEATURE 👍  @supu2701 

https://user-images.githubusercontent.com/74768430/102536856-30bd0000-40d0-11eb-8559-138b745e01d5.mp4

**Comment by supu2701** [comment]
> @supu2701 is the code working fine? 😊😊

@shivjyotigarai . There is a change which need to be made. Currently, the sliding feature is added such that the the activity is changing from the current activity to the previous/next activity, i.e opening up the next activity.
Make the sliding feature such that there is animation i.e slide animations between the activities. Mostly all apps make use of the sliding animation to insert sliding features between the activities. 
For reference you can go through the following video.
https://youtu.be/0s6x3Sn4eYo 
Hope you understand. In case of any queries feels free to ask.

**Comment by shivjyotigarai** [comment]
> > @supu2701 is the code working fine? 😊😊
> 
> @shivjyotigarai . There is a change which need to be made. Currently, the sliding feature is added such that the the activity is changing from the current activity to the previous/next activity, i.e opening up the next activity.
> Make the sliding feature such that there is animation i.e slide animations between the activities. Mostly all apps make use of the sliding animation to insert sliding features between the activities.
> For reference you can go through the following video.
> https://youtu.be/0s6x3Sn4eYo
> Hope you understand. In case of any queries feels free to ask.

ok working on it

**Pull request closed without merging**
