### PR TITLE
fixed enable location dialog

### PR DESCRIPTION
**Pull request by ASVKVINAYAK**
I tried to show enable location dialog box and i fixed it.
But location was not showing so i got confused and i thought that my code is somewhere wrong as in video location was displaying. But i did not get it so i left it.
I am sharing the video of the fixed issue please check it i have done correctly or not.

WhatsApp-Video-2020-12-16-at-112

### CODE REVIEW

**Comment by shivjyotigarai** [comment]
go to do something with the API key...plz check in the developers console whether Maps Activity is enabled or not...or else the map will not show up :)

**Comment by ASVKVINAYAK** [comment]
Ok I will check it

**Comment by supu2701** [comment]
@ASVKVINAYAK  First of all Congratulations, you have done the job correctly. Your task was only to implement the location dialog box in case the device location is turned on which you have performed well. The problem of location not showing up in "Nearby places" is a known bug  which I have already mentioned in another issue #13 . 
I am willing to merge your PR But your fork is not updated and a lot has happened since the current state of your fork (including the commit made by you) in which you excluded some files from the repository by updating them in the .gitignore file. merging this PR will again add those files to the repository. Secondly a file is also conflicting (.idea/misc.xml) which should not have conflicted if your repo and hence .gitignore file was updated.
So, I will recommend you to update your fork and copy paste the changes you made (in MapsActivity.java and build.gradle) and then create a seperate pull request which I will be happy to merge.
Also in future try to update your fork to the current state before you start working on an issue. Upon doing this, you would be making changes in the updated code i.e the code which is free from issues which had already been created and merged in the master branch
Hence, kindly copy paste the changes and make a new PR from updated fork, so as to make your PR so that I can merge it.

**Comment by shivjyotigarai** [comment]
@supu2701  Is my fork updated or would i have to do the same thing regarding the swipe screen feature PR:)

**Comment by ASVKVINAYAK** [comment]
i was trying to fix issue so i made a new branch as if i can cghange the code not disturb the master branch.
Ok i will add the code in master branch and make a pr

**Pull request closed without merging**
